pipeline {
    agent any

    environment {
        RESOURCE_GROUP = 'test'
        AKS_CLUSTER_NAME = 'myakscluster'
        KUBECONFIG = '~/.kube/config'
        ARM_SUBSCRIPTION_ID=credentials('azure-subscription-id')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/NarjesTaghlet/Nginx_Deployment.git'
            }
        }


        stage('Azure Login') {
            steps {
                script {
                    sh '''
                        az login --use-device-code
                        az account set --subscription $ARM_SUBSCRIPTION_ID
                        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME --file $KUBECONFIG
                    '''
                }
            }
        }

        stage('Deploy NGINX Pod') {
            steps {
                sh 'kubectl apply -f nginx-deployment.yaml'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -o wide'
                sh 'kubectl get deployments'
            }
        }
    }
}